version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - checkout

  deploy:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install function dependencies
          command: cd functions;npm install;cd ..
      - run:
          name: Install firebase tools
          command: npm install --save-dev firebase-tools
      - run:
          name: Set firebase config variables
          command: ./node_modules/.bin/firebase functions:config:set bundle.id=$BUNDLE_ID twilio.token=$TWILIO_TOKEN twilio.sid=$TWILIO_SID dynamiclink.key=$FIREBASE_KEY coinbase.key=$COINBASE_KEY coinbase.secret=$COINBASE_SECRET coinbase.btc=$COINBASE_BTC_ACCOUNT coinbase.bch=$COINBASE_BCH_ACCOUNT coinbase.eth=$COINBASE_ETH_ACCOUNT coinbase.ltc=$COINBASE_LTC_ACCOUNT slack.url=$SLACK_URL
      - run:
          name: Firebase deploy
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --non-interactive


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
